SELECT * WHERE {  ?v1 <http://www.geonames.org/ontology#parentCountry> <http://db.uwaterloo.ca/~galuc/wsdbm/Country15> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v3 .  }
